name: 'advgen_demo'
version: '0.1.0'
config-version: 2

profile: 'advgen_demo'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
clean-targets: ["target", "dbt_packages"]

vars:
  hash: sha

seeds:
  advgen_demo:
    +schema: raw
    crm_customer:
      +column_types:
        customer_id: varchar(20)
        customer_name: varchar(100)
        email: varchar(200)
        phone: varchar(20)
        address: varchar(200)
        updated_at: timestamp
        crm_ingested_at: timestamp

models:
  advgen_demo:
    staging:
      +materialized: view
      +schema: staging

    raw_vault:
      +materialized: incremental
      +schema: raw_vault
      +on_schema_change: fail
